CREATE TABLE IF NOT EXISTS employees (
  id uuid,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  phone VARCHAR(15) UNIQUE NOT NULL,
  password VARCHAR(512) NOT NULL,
  avatar VARCHAR(512) NOT NULL,
  position VARCHAR(100) NOT NULL,
  salary  INT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);
