version: "3.0"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/clean_web
    env_file: .env
    container_name: graphql-web
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    container_name: graphql-db
    ports:
      - 54320:${DB_PORT}
    volumes:
      - graphql_db:/var/lib/postgresql

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080

volumes:
  graphql_db:
